from colmap_manage.Module.colmap_manager import COLMAPManager
from colmap_manage.Module.dataset_manager import DatasetManager

gs_list = ['haizei_1', 'haizei_1_v2', 'haizei_1_v3', 'shuijiao_1', 'high_detail_1']

for gs_data in gs_list:
    if gs_data != 'haizei_1_v3':
        continue

    data_folder_path = "/home/lichanghao/chLi/Dataset/GS/" + gs_data + "/"
    video_file_path = "/home/lichanghao/chLi/Dataset/GS/" + gs_data + ".MOV"
    #video_file_path = None
    target_image_num = 100

    scale = 1
    show_image = False
    print_progress = True
    remove_old = False
    remain_db = True
    valid_percentage = 0.8
    run_mvs = False
    dataset_folder_path = data_folder_path
    method_dict = {}
    is_copy = True

    COLMAPManager(
        data_folder_path,
        video_file_path,
        target_image_num,
        scale,
        show_image,
        print_progress,
    ).autoGenerateData(
        remove_old, remain_db, valid_percentage, run_mvs=run_mvs
    )

    DatasetManager().generateDataset(
    "gs", data_folder_path, dataset_folder_path, method_dict, is_copy, print_progress
    )
    #DatasetManager().autoGenerateDataset(
    #    data_folder_path, dataset_folder_path, is_copy, print_progress
    #)
