from colmap_manage.Module.colmap_manager import COLMAPManager
from colmap_manage.Module.dataset_manager import DatasetManager

nerf_list = ['chair', 'hotdog', 'mic', 'ship']
nerf_list = ['hotdog', 'ship']

for nerf in nerf_list:
    data_folder_path = "/home/chli/Dataset/NeRF/" + nerf + "_train/"
    dataset_folder_path = "../colmap-manage/output/" + nerf + "_train/"
    remove_old = False
    remain_db = True
    valid_percentage = 0.8
    run_mvs = False
    is_copy = False
    print_progress = True

    COLMAPManager(data_folder_path).autoGenerateData(
        remove_old, remain_db, valid_percentage, run_mvs=run_mvs
    )

    DatasetManager().autoGenerateDataset(
        data_folder_path, dataset_folder_path, is_copy, print_progress
    )
