from colmap_manage.Module.colmap_manager import COLMAPManager

nerf_list = ['chair', 'drums', 'ficus', 'hotdog', 'lego', 'materials', 'mic', 'ship']

for nerf in nerf_list:
    data_folder_path = "/home/chli/Dataset/NeRF/" + nerf + "_train/"
    remove_old = False
    remain_db = True
    valid_percentage = 0.8

    COLMAPManager(data_folder_path).autoGenerateData(
        remove_old, remain_db, valid_percentage
    )
