from colmap_manage.Module.colmap_manager import COLMAPManager
from colmap_manage.Module.dataset_manager import DatasetManager

data_root_folder_path = "/home/chli/Dataset/DTU/split_images/"
scene_id = 110
split_tag = 'max'

data_folder_path = data_root_folder_path + str(scene_id) + "/" + split_tag + "/"

remove_old = False
remain_db = True
valid_percentage = 0.8
run_mvs = False
dataset_folder_path = "../colmap-manage/output/dtu_" + str(scene_id) + "_" + split_tag + "/"
is_copy = False
print_progress = True

COLMAPManager(data_folder_path).autoGenerateData(
    remove_old, remain_db, valid_percentage, run_mvs=run_mvs
)
# DatasetManager().generateDataset(
#    "gs", data_folder_path, dataset_folder_path, method_dict, is_copy, print_progress
# )
DatasetManager().autoGenerateDataset(
    data_folder_path, dataset_folder_path, is_copy, print_progress
)
