from colmap_manage.Module.colmap_manager import COLMAPManager


def demo():
    data_folder_path = '/home/chli/chLi/Dataset/NeRF/3vjia_simple/'
    video_file_path = '/home/chli/chLi/Dataset/NeRF/3vjia_person_2/1.mp4'
    down_sample_scale = 4
    scale = 1
    show_image = False
    print_progress = True
    remove_old = False
    valid_percentage = 0.8

    colmap_manager = COLMAPManager(data_folder_path, video_file_path, down_sample_scale,
                                   scale, show_image, print_progress)
    colmap_manager.autoGenerateData(remove_old, valid_percentage)
    return True
